Septik.Web/Models/CityAddEditVM.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Septik.Web.Models
{
    public class CityAddEditVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
    }
}

Septik.Web/Models/CityDetailsVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Septik.Web.Models
{
    public class CityDetailsVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
    }
}

Septik.Web/Models/CityItemVM.cs
using Septik.Web.Data.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Septik.Web.Models
{
    public class CityItemVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<CityImage> Images { get; set; }
    }
}

Septik.Web/Models/ErrorViewModel.cs
using System;

namespace Septik.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Septik.Web/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Septik.Web.Data;
using Septik.Web.Data.Entities;
using Septik.Web.Models;

namespace Septik.Web.Controllers
{
    public class CitiesController : Controller
    {
        // Create a field to store the mapper object
        private readonly IMapper _mapper;
        private readonly ApplicationDbContext _context;

        // Assign the object in the constructor for dependency injection
        public CitiesController(IMapper mapper, 
            ApplicationDbContext context)
        {
            _mapper = mapper;
            _context = context;
        }
        // GET: CitiesController
        public ActionResult Index()
        {
            var cities = _context.Cities.Select(x=>new CityItemVM() {Name = x.Name, Images = _context.CityImages.Where(t=>t.CityId == x.Id).ToList() }); 
            var dto = _mapper.Map<IEnumerable<CityItemVM>>(cities);
            return View(dto);
        }

        // GET: CitiesController/Details/5
        public ActionResult Details(int id)
        {
            var entity = _context.Cities.SingleOrDefault(c => c.Id == id);
            if(entity != null)
            {
                var model = _mapper.Map<CityDetailsVM>(entity);
                return View(model);
            }
            return NotFound();
        }

        // GET: CitiesController/Create
        public ActionResult Create()
        {
            return View();
        }

        public Image Base64ToImage(string base64String)
        {
            // Convert base 64 string to byte[]
            byte[] imageBytes = Convert.FromBase64String(base64String.Split(',')[1]);
            // Convert byte[] to Image
            using (var ms = new MemoryStream(imageBytes, 0, imageBytes.Length))
            {
                Image image = Image.FromStream(ms, true);
                return image;
            }
        }

        // POST: CitiesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CityAddEditVM cityAddEdit, 
            string [] cityImages)
        {
            try
            {
                //string extension;
                //extension = Path.GetExtension(file.FileName);
                ////string f
                //string name = Path.GetRandomFileName() + extension;
                //var path = Path.Combine(
                // Directory.GetCurrentDirectory(), "Uploads", name);
                //using (var stream = new FileStream(path, FileMode.Create))
                //{
                //    await file.CopyToAsync(stream);
                //}

                //var entity = _mapper.Map<City>(cityAddEdit);
                //entity.Image = name;
                //_context.Cities.Add(entity);
                //_context.SaveChanges();

                //return RedirectToAction(nameof(Index));
                //List<CityImage> images = new List<CityImage>();

                var model = new City()
                {
                    Name = cityAddEdit.Name,
                    Lat = cityAddEdit.Lat,
                    Lng = cityAddEdit.Lng,
                    Image = "image"
                };

                _context.Cities.Add(model);
                _context.SaveChanges();
                var entity = _mapper.Map<City>(cityAddEdit);
                foreach (var item in cityImages)
                {
                    Image file = Base64ToImage(item);
                    string extension = ".jpg";
                    string name = Path.GetRandomFileName() + extension;
                    var path = Path.Combine(
                    Directory.GetCurrentDirectory(), "Uploads", name);
                   

                    file.Save(path, ImageFormat.Jpeg);

                    var image = new CityImage();
                    image.Name = name;
                    image.CityId = model.Id;
                    _context.CityImages.Add(image);
                    _context.SaveChanges();
                }
                

                _context.Cities.Add(entity);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));

            }
            catch(Exception ex)
            {
                return View(cityAddEdit);
            }
        }

        // GET: CitiesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CitiesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CitiesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CitiesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Septik.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Septik.Web.Models;

namespace Septik.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Septik.Web/Views/Cities/Create.cshtml
@model Septik.Web.Models.CityAddEditVM

@{
    ViewData["Title"] = "Create";
}

@section Styles {

    <link href="~/lib/cropperjs/dist/cropper.min.css" rel="stylesheet" />
    <link href="~/css/scss/stackPhoto.min.css" rel="stylesheet" />

}

<h1>Додати місто</h1>

<hr />
<div class="row">
    <div class="col-md-5">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(x => x.Id)
            @*<div class="form-group">
            <label asp-for="Id" class="control-label"></label>
            <input asp-for="Id" class="form-control" />
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <partial name="_StackPhoto" />

            @*<div class="custom-file">
                <input type="file" class="custom-file-input" name="file" id="file">
                <label class="custom-file-label" for="customFile">Оберіть фото міста</label>
            </div>*@
            <br />
            <br />
            @Html.HiddenFor(x => x.Lat)
            @Html.HiddenFor(x => x.Lng)
            <div class="form-group">
                <input type="submit" value="Створити магазин" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col-md-7">
        @*<h2>Позначте точну на карті вашого міста</h2>*@
        <div id="map" class="w-100 h-100"></div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<partial name="_CropperModal" />




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="~/lib/cropperjs/dist/cropper.min.js"></script>

    <script>
        var lat = 50.618778, lng = 26.258798;
        let $Lat = $("#Lat");
        let $Lng = $("#Lng");
        $Lat.val(lat);
        $Lng.val(lng);
        var map = L.map('map').setView([lat, lng], 13);

        var marker = L.marker([lat, lng],
            { title: "MyPoint", alt: "The Big I", draggable: true }).addTo(map)
            .bindPopup('Шаг Академія');

        marker.on('dragend', function () {
            console.log("Hello ", marker.getLatLng());
            $Lat.val(marker.getLatLng().lat);
            $Lng.val(marker.getLatLng().lng);
            //var coord = String(marker.getLatLng()).split(',');
            //console.log(coord);
            //var lat = coord[0].split('(');
            //console.log(lat);
            //var lng = coord[1].split(')');
            //console.log(lng);
            //marker.bindPopup("Moved to: " + lat[1] + ", " + lng[0] + ".");
        });


        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);


                    //.openPopup();
    </script>



    <script>
        $(document).ready(function () {
            let cropper;
            let dialogCropper = $("#cropperModal");
            //generateID();
            initCropper();
            //загрузка фото на клік
            uploadImage();
            //загрузка фото на клік
            function uploadImage() {
                let button = $('.images .pic');

                let images = $('.images');

                button.on('click', function () {
                    let uploader = $('<input type="file" accept="image/*" />');
                    uploader.click()
                    uploader.on('change', function () {
                        let reader = new FileReader();
                        reader.onload = function (event) {

                            dialogCropper.modal('show');
                            cropper.replace(event.target.result);
                            uploader.remove();
                            //
                        };
                        reader.readAsDataURL(uploader[0].files[0]);

                    });
                });

                images.on('click', '.img', function () {
                    $(this).remove();
                });

                //обрізка малюнка
                $("#cropImg").on("click", function (e) {
                    e.preventDefault();
                    var imgContent = cropper.getCroppedCanvas().toDataURL();

                    images.prepend(`
                                      <div class="img" style="background-image: url(${imgContent});" 
                                            rel="${imgContent}">
                                                <span>remove</span>
                                                <input type="hidden" name="cityImages[]" value="${imgContent}">
                                       </div>`);
                    dialogCropper.modal('hide');
                });

            }

            function initCropper() {
                //запуск кропера
                const imageCropper = document.getElementById('imageCropper');
                cropper = new Cropper(imageCropper, {
                    aspectRatio: 420 / 320,
                    viewMode: 1,
                    autoCropArea: 0.5,
                    crop(event) {
                        // console.log(event.detail.x);
                        // console.log(event.detail.y);
                        // console.log(event.detail.width);
                        // console.log(event.detail.height);
                        // console.log(event.detail.rotate);
                        // console.log(event.detail.scaleX);
                        // console.log(event.detail.scaleY);
                    },
                });
            }
        });


    </script>

}

Septik.Web/Views/Cities/Details.cshtml
@model Septik.Web.Models.CityDetailsVM

@{
    ViewData["Title"] = "Details";
}

<h1>@Model.Name</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-6">
            <img src="@Model.Image" width="400" alt="Фото" />
        </dt>
        <dd class="col-sm-6">
            <h2>На карті</h2>
            <div id="map" class="w-100 h-100"></div>
        </dd>

    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>


@section Scripts {


    <script>
        var lat = @Model.Lat, lng = @Model.Lng;
        
        var map = L.map('map').setView([lat, lng], 16);

        var marker = L.marker([lat, lng],
            { title: "MyPoint", alt: "The Big I", draggable: true }).addTo(map)
            .bindPopup('@Model.Name');

        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);


            //.openPopup();
    </script>
}

Septik.Web/Views/Cities/Index.cshtml
@model IEnumerable<Septik.Web.Models.CityItemVM>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            @*<th>
                @Html.DisplayNameFor(model => model.Image)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <img src="images/@item.Images[0].Name" width="200" alt="Фото" />
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new {  id=item.Id  }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

Septik.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Septik.Web/Views/Shared/_CropperModal.cshtml
<!-- Modal -->
<div class="modal" id="cropperModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div>
                    <img id="imageCropper" src="~/img/upload.png" height="400">
                </div>
            </div>
            <div class="modal-footer">
                <a id="img-rotation" class="btn btn-success"><i class="fa fa-repeat" aria-hidden="true"></i></a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button id="cropImg" class="btn btn-primary">Обрізати фото</button>
            </div>
        </div>
    </div>
</div>

Septik.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Septik.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/leaflet/dist/leaflet.css" rel="stylesheet" />
    <script src="~/lib/leaflet/dist/leaflet.js"></script>
    @RenderSection("Styles", required: false)
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Septik.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cities" asp-action="Index">Міста</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Septik.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Septik.Web/Views/Shared/_StackPhoto.cshtml
<div class="stackPhoto">
    <div class="wrapper">
        <div class="images">
            <div class="pic">
                Додати фото
            </div>

        </div>
    </div>
</div>